## Numpy 

In [1]:
import numpy as np

#### Numpy DataTypes

In [2]:
array1 = np.array([2,4,6,8,10])
array1

array([ 2,  4,  6,  8, 10])

In [3]:
a2 = np.array([[1,2,3,4],
                [5,6,7,8]])
a3 = np.array([[[1,2,3,4],
                [5,6,7,8]],
                [[9,10,11,12],
                 [14,15,16,17]]])

In [4]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [14, 15, 16, 17]]])

In [6]:
a3.shape

(2, 2, 4)

In [7]:
a2.shape

(2, 4)

In [8]:
array1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [9]:
array1.size,a2.size,a3.size

(5, 8, 16)

In [10]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Create a DataFrame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

#### Creating arrays

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
df2 = pd.DataFrame(ones)
df2

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0

In [14]:
type(ones)

numpy.ndarray

In [15]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(2,10,2)
range_array

array([2, 4, 6, 8])

In [17]:
random_array = np.random.randint(2,10, size=(3,5))
random_array

array([[8, 8, 9, 5, 5],
       [5, 4, 7, 7, 3],
       [6, 5, 4, 6, 8]])

In [18]:
random_array.shape

(3, 5)

In [19]:
np.random.seed(4)
r3 = np.random.random(size=(5,4))
r3

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394],
       [0.0089861 , 0.38657128, 0.04416006, 0.95665297]])

In [20]:
np.unique(r3)

array([0.00623026, 0.0089861 , 0.04416006, 0.16384224, 0.19768507,
       0.2160895 , 0.25298236, 0.38657128, 0.43479153, 0.54723225,
       0.59733394, 0.69772882, 0.71481599, 0.77938292, 0.86299324,
       0.95665297, 0.96702984, 0.97268436, 0.97627445, 0.98340068])

In [21]:
a3[1]

array([[ 9, 10, 11, 12],
       [14, 15, 16, 17]])

In [22]:
r4 = np.random.randint(10, size=(2,3,4,5))
r4

array([[[[8, 1, 2, 7, 0],
         [8, 3, 1, 0, 3],
         [2, 3, 2, 9, 2],
         [1, 0, 1, 9, 9]],

        [[0, 7, 2, 6, 3],
         [7, 8, 2, 6, 7],
         [7, 9, 2, 7, 5],
         [3, 0, 5, 4, 3]],

        [[8, 9, 5, 8, 6],
         [7, 0, 4, 6, 8],
         [4, 8, 1, 9, 5],
         [4, 2, 3, 4, 7]]],


       [[[6, 6, 8, 0, 3],
         [5, 6, 1, 1, 6],
         [0, 8, 7, 5, 7],
         [6, 8, 4, 4, 0]],

        [[7, 2, 1, 8, 8],
         [1, 3, 1, 3, 6],
         [7, 4, 0, 7, 3],
         [7, 9, 6, 6, 9]],

        [[3, 2, 7, 6, 7],
         [9, 4, 3, 0, 5],
         [0, 9, 5, 7, 5],
         [9, 8, 2, 4, 2]]]])

In [23]:
# getting the first number in the innermost
r4[:, :, :, :2]

array([[[[8, 1],
         [8, 3],
         [2, 3],
         [1, 0]],

        [[0, 7],
         [7, 8],
         [7, 9],
         [3, 0]],

        [[8, 9],
         [7, 0],
         [4, 8],
         [4, 2]]],


       [[[6, 6],
         [5, 6],
         [0, 8],
         [6, 8]],

        [[7, 2],
         [1, 3],
         [7, 4],
         [7, 9]],

        [[3, 2],
         [9, 4],
         [0, 9],
         [9, 8]]]])

#### Manipulation & comparing arrays

##### Arithmetic

In [24]:
a1 = np.array([1, 2, 3])
ones1 = np.ones((3))

In [25]:
a1

array([1, 2, 3])

In [26]:
ones1

array([1., 1., 1.])

In [27]:
a1 + ones1

array([2., 3., 4.])

In [28]:
a1 - ones1

array([0., 1., 2.])

In [29]:
a1 * ones1

array([1., 2., 3.])

In [30]:
a2 * a3

array([[[  1,   4,   9,  16],
        [ 25,  36,  49,  64]],

       [[  9,  20,  33,  48],
        [ 70,  90, 112, 136]]])

In [31]:
a3 % a2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 2, 0],
        [4, 3, 2, 1]]])

In [32]:
a3 / a2

array([[[1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        ]],

       [[9.        , 5.        , 3.66666667, 3.        ],
        [2.8       , 2.5       , 2.28571429, 2.125     ]]])

In [33]:
a3.T

array([[[ 1,  9],
        [ 5, 14]],

       [[ 2, 10],
        [ 6, 15]],

       [[ 3, 11],
        [ 7, 16]],

       [[ 4, 12],
        [ 8, 17]]])

In [34]:
np.random.seed(0)

n1 = np.random.randint(5, size=(3,4))
n2 = np.random.randint(5, size=(3,4))


In [35]:
n1

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 0, 0, 4]])

In [36]:
n2

array([[2, 1, 0, 1],
       [1, 0, 1, 4],
       [3, 0, 3, 0]])

In [37]:
n3 = np.dot(n1, n2.T)

In [38]:
n3

array([[11, 19, 21],
       [ 9, 14, 18],
       [12, 20, 12]])

#### Dot product example (nut butter sale)

In [39]:
np.random.seed(0)

#num of jars sold
sale_amount = np.random.randint(20, size=(5,3))
sale_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [40]:
# creating weekly DataFrame
weekly_sales = pd.DataFrame(sale_amount, index=["Mon", "Tue", "Wed", "Thurs", "Fri"], 
                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [41]:
# Creating price array
prices = np.array([10, 78, 12])
prices

array([10, 78, 12])

In [42]:
# creat butter prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10             78             12

In [43]:
total_sales = prices.dot(sale_amount.T)
total_sales

array([1290,  348, 1788,  652,  562])

In [44]:
# Create daily sales
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue   Wed  Thurs  Fri
Price  1290  348  1788    652  562

In [45]:
weekly_sales["Total ($)"] = daily_sales.T

In [46]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0       1290
Tue                3              3              7        348
Wed                9             19             18       1788
Thurs              4              6             12        652
Fri                1              6              7        562

## Sorting Arrays

In [47]:
random_array

array([[8, 8, 9, 5, 5],
       [5, 4, 7, 7, 3],
       [6, 5, 4, 6, 8]])

In [48]:
random_array.shape

(3, 5)

In [49]:
np.sort(random_array)

array([[5, 5, 8, 8, 9],
       [3, 4, 5, 7, 7],
       [4, 5, 6, 6, 8]])

In [50]:
np.argsort(random_array)

array([[3, 4, 0, 1, 2],
       [4, 1, 0, 2, 3],
       [2, 1, 0, 3, 4]], dtype=int64)

In [51]:
np.argsort(array1)

array([0, 1, 2, 3, 4], dtype=int64)

In [54]:
np.argmin(a2)

0

In [57]:
np.argmax(random_array, axis=1)

array([2, 2, 4], dtype=int64)

In [58]:
np.argmax(random_array, axis=0)

array([0, 0, 0, 1, 2], dtype=int64)