# Scikit-Learn (sklearn)

### Introduction to scikit-learn 

This notebook demonstrate some of the most useful functions of the beautiful Scikit-Learn Library

##### What I'm going to cover:
0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
3. Choosing the right estimator/algorithm for our problems
4. Fit the model/algorithm and use it to make predictions on our data
5. Evaluating the model
6. Save and load the model
7. Putting it all together!

## 0. An end-to-end Scikit-Learn workflow

In [56]:
# 1. Get the data ready
import pandas as pd
import numpy as np

In [39]:
heart_disease = pd.read_csv('heart-disease-data2.csv')
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [40]:
# Create X (features matrix)
X = heart_disease.drop("target", axis=1)

# Create y(Labels)
y = heart_disease["target"]

In [41]:
# choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# Get default hyperprarameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [42]:
# Fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [43]:
clf.fit(X_train, Y_train);

In [46]:
# predict
y_label = clf.predict(X_test)
y_label

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [47]:
y_predicts = clf.predict(X_train)
y_predicts

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1],
      dtype=int64)

In [48]:
Y_test

16     1
55     1
169    0
153    1
203    0
      ..
175    0
263    0
32     1
217    0
193    0
Name: target, Length: 61, dtype: int64

In [52]:
y_preds = clf.predict(X_test)
y_preds

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [49]:
# Evaluate model on training data and test data
clf.score(X_train, Y_train)


1.0

In [50]:
clf.score(X_test, Y_test)

0.8360655737704918

In [53]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test, y_pred=y_preds))

              precision    recall  f1-score   support

           0       0.86      0.81      0.83        31
           1       0.81      0.87      0.84        30

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



In [54]:
confusion_matrix(Y_test, y_preds)

array([[25,  6],
       [ 4, 26]], dtype=int64)

In [55]:
accuracy_score(Y_test, y_preds)

0.8360655737704918

In [58]:
# %. Impove model
# Trying different amount of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators....")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, Y_test)*100:.2f}%")
    print("")
print("........Ended........")

Trying model with 10 estimators....
Model accuracy on test set: 83.61%

Trying model with 20 estimators....
Model accuracy on test set: 80.33%

Trying model with 30 estimators....
Model accuracy on test set: 83.61%

Trying model with 40 estimators....
Model accuracy on test set: 83.61%

Trying model with 50 estimators....
Model accuracy on test set: 85.25%

Trying model with 60 estimators....
Model accuracy on test set: 86.89%

Trying model with 70 estimators....
Model accuracy on test set: 83.61%

Trying model with 80 estimators....
Model accuracy on test set: 86.89%

Trying model with 90 estimators....
Model accuracy on test set: 86.89%

........Ended........


In [59]:
# Save model and load it
import pickle

pickle.dump(clf, open("random_forest_model.pkl", "wb"))

In [64]:
model = pickle.load(open("random_forest_model.pkl", "rb"))
model.score(X_test, Y_test)

0.8688524590163934